name: Continuous Integration
on: [push]
jobs:
  call-continuous-integration-reusable:
    uses: devops-prac1/github-reusable-workflows/.github/workflows/ci.yml@main
    with:
      project_name: expense-frontend
      secrets: inherit
    #